export const CREATE = "CREATE"
export const UPDATE = "UPDATE"
export const DELETE = "DELETE"
export const FETCH_ALL = "FETCH_ALL"
export const LIKE = "LIKE"
export const FETCH_BY_SEARCH = " FETCH_BY_SEARCH"
export const LOADING_TRUE = "LOADING_TRUE"
export const LOADING_FALSE = "LOADING_FALSE"

export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"
